### ISSUE TITLE
__init__() got an unexpected keyword argument 'biometric_weight'

### ISSUE THREAD

**Issue by baiyun442** [sudban3089/ID-Preserving-Facial-Aging#5]
when I train the Cosine loss，there has a TypeError:

` python main.py --base configs/stable-diffusion/v1-finetune_cosineloss.yaml -t  --actual_resume stable-diffusion/v1-5-pruned.ckpt   -n test1 --gpus 0,  --data_root  IJCB2023_TrainExamples/SubID_0029_NumImages_19/ --reg_data_root CelebA_regularization_NEW/ --class_word person --no-test

Global seed set to 23
Running on GPUs 0,
Loading model from stable-diffusion/v1-5-pruned.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Traceback (most recent call last):
  File "main.py", line 638, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 29, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/aiyun/ID-Preserving-Facial-Aging-main/ID-Preserving-Facial-Aging-main/ldm/util.py", line 86, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "/home/aiyun/ID-Preserving-Facial-Aging-main/ID-Preserving-Facial-Aging-main/ldm/models/diffusion/ddpm_cosineembedding.py", line 483, in __init__
    self.instantiate_first_stage(first_stage_config)
  File "/home/aiyun/ID-Preserving-Facial-Aging-main/ID-Preserving-Facial-Aging-main/ldm/models/diffusion/ddpm_cosineembedding.py", line 543, in instantiate_first_stage
    model = instantiate_from_config(config)
  File "/home/aiyun/ID-Preserving-Facial-Aging-main/ID-Preserving-Facial-Aging-main/ldm/util.py", line 86, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
TypeError: __init__() got an unexpected keyword argument 'biometric_weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 851, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined
`
why does it happen? what should I do？ Any suggestions?

**Comment by sudban3089** [comment]
I have commented out `biometric_weight` in v1-finetune_cosineloss.yaml (Line 57) as that was not defined or needed in ddpm_cosineembedding.py. Hope this solves the issue.

**Comment by baiyun442** [comment]
It works! Thank you!
